### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by scottmc**

### CODE REVIEW

**Comment by scottmc** [comment]
Please check over this and the documentation seen when running the program.  Left me know if there's anything that should be fixed before the 5.1.1 release.  Text that affects catkeys will likely not be changed until after this release.  

Really strange issue...
With a fresh git clone in a new directory....
Build with HaikuR1B3 both X86_gcc2 and X86 and everything looks good, version listed in the About Window is 5.1.1
Build with HaikuR1B3 x86_64 and the version listed in the About Window is 5.1
Build with Haiku Nightly x86_64 and the version listed in the About Window is 5.1.1

Anyone have any idea why this would happen?  Can anyone confirm this happens or doesn't for them?

**Comment by humdingerb** [comment]
Tiny correctio to changelog.txt : Croatian (hr) hasn't yet been added, its translation hasn't reached 80% yet.

WRT your About version confusion, maybe you have an old v5.1 binary laying around in HaikuR1B3 x86_64?

**Comment by humdingerb** [comment]
The changelog.txt could also mention the "Added split view for better GUI control".

**Comment by scottmc** [comment]
> WRT your About version confusion, maybe you have an old v5.1 binary laying around in HaikuR1B3 x86_64?
That was it!  Deleted all armyknife binaries on that VM and did a make clean, then make and it was fixed, now showing as 5.1.1 there.

**Comment by scottmc** [comment]
@humdingerb check over my latest changes and if ok then merge.  I fixed the conflict with #71.

**Comment by humdingerb** [comment]
LGTM.

**Pull request merged**
