### PR TITLE
Create Help menu

### LINKED ISSUE #22: No Help menu
There seems to be no help menu for ArmyKnife. For an app that has menu not self-explanatory it may seem better to explain what they do.
screenshot8

### PR DESCRIPTION
**Pull request by eddrda**
Help menu contains readme & changelog files, which are put in `/boot/system/apps/ArmyKnife/Documentation`
Should fix #22 
  
  
capture

### CODE REVIEW

**Comment by scottmc** [comment]
Read up on FindDirectory and then update this pull request to make use of it, instead of hard coding the directories.
https://github.com/haikuports/haikuports/wiki/FindDirectory

**Comment by humdingerb** [comment]
The recipe for ArmyKnife puts the docs in a folder alongside the binary. This can be in the system or in the home hierarchy. It's best to open the docs relative to the binaries location. Have a look at the main.cpp of Filer here at HaikuArchive for an example how that can be done.

**Comment by eddrda** [comment]
Modified to use BPath & find_directory.

**Comment by humdingerb** [comment]
This will not work.
The recipe puts the readme in $appsDir/Documentation. No "armyknife" subfolder.
It also won't work when installing in the "Home" hierarchy, as B_APPS_DIRECTORY will return /system/apps/ first. You could iterate thru all possible locations with PathFinder()....

I did comment on having a look at "Filer" for a reason...

**Comment by janus2** [comment]
I think it could be awesome if we add in a known place a css and maybe a html template. So all the guide, tutorial and help looks alike. The filer and preinstalled apps documentation looks stunning.

**Pull request merged**
